import { Category } from "@/model/category";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const categories: Category[] = await fetch(`${process.env.NEXT_PUBLIC_SERVER_DOMAIN}/categories?isActive=true`, {
    next: {
      revalidate: Number(process.env.NEXT_PUBLIC_REVALIDATE),
    },
  })
    .then((res) => res.json())
    .catch((err) => {
      console.error(err);
      return [];
    });
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <header className="header">
            <h1>{process.env.NEXT_PUBLIC_BRAND_NAME}</h1>
            <div className="user">
              <div className="cart">
                <svg
                  className="cart-icon"
                  xmlns="http://www.w3.org/2000/svg"
                  width="800px"
                  height="800px"
                  viewBox="0 0 24 24"
                  fill="none"
                >
                  <path
                    d="M3.864 16.4552C4.40967 18.6379 4.68251 19.7292 5.49629 20.3646C6.31008 21 7.435 21 9.68486 21H14.3155C16.5654 21 17.6903 21 18.5041 20.3646C19.3179 19.7292 19.5907 18.6379 20.1364 16.4552C20.9943 13.0234 21.4233 11.3075 20.5225 10.1538C19.6217 9 17.853 9 14.3155 9H9.68486C6.14745 9 4.37875 9 3.47791 10.1538C2.94912 10.831 2.87855 11.702 3.08398 13"
                    stroke="#1C274C"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                  />
                  <path
                    d="M19.5 9.5L18.7896 6.89465C18.5157 5.89005 18.3787 5.38775 18.0978 5.00946C17.818 4.63273 17.4378 4.34234 17.0008 4.17152C16.5619 4 16.0413 4 15 4M4.5 9.5L5.2104 6.89465C5.48432 5.89005 5.62128 5.38775 5.90221 5.00946C6.18199 4.63273 6.56216 4.34234 6.99922 4.17152C7.43808 4 7.95872 4 9 4"
                    stroke="#1C274C"
                    strokeWidth="1.5"
                  />
                  <path
                    d="M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4C15 4.55228 14.5523 5 14 5H10C9.44772 5 9 4.55228 9 4Z"
                    stroke="#1C274C"
                    strokeWidth="1.5"
                  />
                </svg>

                <div className="cart-count">10</div>
              </div>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                fill="#000000"
                version="1.1"
                id="Layer_1"
                width="800px"
                height="800px"
                viewBox="796 796 200 200"
                enableBackground="new 796 796 200 200"
                xmlSpace="preserve"
              >
                <g>
                  <path d="M896.003,827.425c-20.538,0-37.187,19.66-37.187,43.921c0,24.258,16.648,43.924,37.187,43.924s37.188-19.667,37.188-43.924   C933.191,847.085,916.541,827.425,896.003,827.425z" />
                  <path d="M896,796c-55.141,0-100,44.859-100,99.999C796.001,951.14,840.86,996,896,996c55.139,0,99.999-44.86,99.999-100.001   C995.999,840.859,951.14,796,896,796z M962.014,953.885c-0.029-0.111-0.044-0.223-0.075-0.333   c-4.735-16.523-15.472-30.494-29.687-39.455c-2.805-1.768-6.442-1.48-8.931,0.71c-7.63,6.719-17.069,10.72-27.319,10.72   c-10.45,0-20.061-4.156-27.767-11.113c-2.46-2.222-6.082-2.556-8.91-0.829c-14.407,8.797-25.353,22.689-30.299,39.192   c-13.012-15.325-20.887-35.145-20.887-56.777c0-48.446,39.414-87.86,87.86-87.86c48.445,0,87.859,39.414,87.859,87.86   C983.859,918.159,975.597,938.412,962.014,953.885z" />
                </g>
              </svg>
            </div>
          </header>
          <nav>
            <ul>
              <li key={0}>
                <Link href={`/`} className="home">
                  TRANG CHỦ
                </Link>
              </li>
              {categories.map((category) => (
                <li key={category._id} className="category-item">
                  <Link href={`/danh-muc/${category.slug}`}>{category.name}</Link>
                  <div className="category-child">
                    {category.child?.map((child) => (
                      <Link key={child._id} href={`/danh-muc/${child.slug}`}>
                        {child.name}
                      </Link>
                    ))}
                  </div>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
        <footer>
          <div className="footer-center">
            <div className="box-footer-column">
              <h3 className="">Thông tin liên hệ:</h3>
              <ul className="footer-list-menu">
                <li className="footer-address"></li>
                <li className="fooer-phone">
                  <label className="mr5">Phone: </label>
                  <span>
                    <Link href={`${process.env.NEXT_PUBLIC_HOTLINE}`}>{process.env.NEXT_PUBLIC_HOTLINE}</Link>
                  </span>
                </li>
                <li className="footer-email">
                  <label className="mr5">Email: </label>
                  <span>{process.env.NEXT_PUBLIC_EMAIL}</span>
                </li>
              </ul>
            </div>

            <div className="box-footer-column">
              <h3 className="">Chính sách hỗ trợ:</h3>
              <ul className="footer-list-menu">
                <li>
                  <a href="/search" title="Tìm kiếm">
                    Tìm kiếm
                  </a>
                </li>

                <li>
                  <a href="/pages/about-us" title="Giới thiệu">
                    Giới thiệu
                  </a>
                </li>

                <li>
                  <a href="/pages/chinh-sach-doi-tra" title="Chính sách đổi trả">
                    Chính sách đổi trả
                  </a>
                </li>

                <li>
                  <a href="/pages/chinh-sach-bao-mat" title="Chính sách bảo mật">
                    Chính sách bảo mật
                  </a>
                </li>

                <li>
                  <a href="/pages/dieu-khoan-dich-vu" title="Điều khoản dịch vụ">
                    Điều khoản dịch vụ
                  </a>
                </li>
              </ul>
            </div>

            <div className="box-footer-column">
              <h3 className="">Thông tin liên kết:</h3>
              <div className="social">
                <ul className="footer-list-menu">
                  <li>Hãy kết nối với chúng tôi.</li>
                </ul>
              </div>
            </div>

            <div className="box-footer-column">
              <h3 className="">Theo dõi Fanpage chúng tôi để cập nhật xu hướng thời trang hot nhất:</h3>
              <div
                className="fb-page fb_iframe_widget"
                data-href="https://www.facebook.com/Vergency.vn"
                data-small-header="false"
                data-adapt-container-width="true"
                data-hide-cover="false"
                data-show-facepile="true"
                fb-xfbml-state="rendered"
                fb-iframe-plugin-query="adapt_container_width=true&amp;app_id=&amp;container_width=263&amp;hide_cover=false&amp;href=https%3A%2F%2Fwww.facebook.com%2FVergency.vn&amp;locale=vi_VN&amp;sdk=joey&amp;show_facepile=true&amp;small_header=false"
              ></div>
            </div>
          </div>

          <div className="footer-bottom">
            <p>©Bản quyền thuộc về {process.env.NEXT_PUBLIC_BRAND_NAME}</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
